# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project_two_development

test:
  <<: *default
  database: project_two_test

production:
  <<: *default
  database: project_two_production
  username: awesome_project_two
  password: <%= ENV['AWESOME_PROJECT_TWO_DATABASE_PASSWORD'] %>


